options = 
{
	{
		default = 5,
		label = "Survival: Build Time", 
		help = "Length of initial building time.", 
		key = 'opt_Survival_BuildTime',
		pref = 'opt_Survival_BuildTime', 
		values = { 
			{text = "0:00",help = "", key = 0, },
			{text = "0:30",help = "", key = 30, }, 
			{text = "1:00",help = "", key = 60, }, 
			{text = "1:30",help = "", key = 90, }, 
			{text = "2:00",help = "", key = 120, }, 
			{text = "2:30",help = "", key = 150, }, 
			{text = "3:00",help = "", key = 180, }, 
			{text = "4:00",help = "", key = 240, }, 
		}, 
	},
	{ 
		default = 9,
		label = "Survival: Unit Count",
		help = "How many enemies attack each minute (per player).", 
		key = 'opt_Survival_EnemiesPerMinute', 
		pref = 'opt_Survival_EnemiesPerMinute', 
		values = {
			{text = "12",help = "", key = 12, },
			{text = "16",help = "", key = 16, },
			{text = "20",help = "", key = 20, },
			{text = "22",help = "", key = 22, },
			{text = "24",help = "", key = 24, },
			{text = "26",help = "", key = 26, },
			{text = "28",help = "", key = 28, },
			{text = "30",help = "", key = 30, },
			{text = "32",help = "", key = 32, },
			{text = "34",help = "", key = 34, },
			{text = "36",help = "", key = 36, },
			{text = "40",help = "", key = 40, },
			{text = "42",help = "", key = 42, },
			{text = "48",help = "", key = 48, },
			{text = "56",help = "", key = 56, },
			{text = "64",help = "", key = 64, },
			{text = "72",help = "", key = 72, },
			{text = "80",help = "", key = 80, },
			{text = "96",help = "", key = 96, },
			{text = "112",help = "", key = 112, },
			{text = "128",help = "", key = 128, },
		}, 
	},
	{ 
		default = 1,
		label = "Survival: Wave Frequency", 
		help = "How long between waves.", 
		key = 'opt_Survival_WaveFrequency', 
		pref = 'opt_Survival_WaveFrequency', 
		values = { 
			{text = "Streaming",help = "", key = 10, },
			{text = "1:00 - Fast Waves",help = "", key = 60, }, 
			{text = "2:00 - Normal Waves",help = "", key = 120, }, 
			{text = "3:00 - Huge Waves",help = "", key = 180, }, 
			{text = "4:00 - Epic Waves",help = "", key = 240, }, 
		},
	},
};
